openapi: 3.0.0
info:
  title: "Magic: The Gathering Card Database API"
  version: 1.0.0
paths:
  /cards:
    get:
      summary: Search cards by different criteria
      parameters:
        - name: name
          in: query
          description: Card name
          schema:
            type: string
        - name: manaCost
          in: query
          description: Mana cost of the card
          schema:
            type: string
        - name: type
          in: query
          description: Card type
          schema:
            type: string
        - name: expansion
          in: query
          description: Expansion name
          schema:
            type: string
        - name: artist
          in: query
          description: Illustration artist
          schema:
            type: string
      responses:
        '200':
          description: List of cards

    post:
      summary: Add a new card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                manaCost:
                  type: string
                type:
                  type: string
                rulesText:
                  type: string
                expansion:
                  type: string
                artist:
                  type: string
                image:
                  type: string
      responses:
        '201':
          description: Card created successfully
        '400':
          description: Bad request

  /cards/{card_id}:
    get:
      summary: Get card information by ID
      parameters:
        - name: card_id
          in: path
          description: ID of the card to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Card information
          content:
            application/json:
              schema:
                type: object

    put:
      summary: Update card information by ID
      parameters:
        - name: card_id
          in: path
          description: ID of the card to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                manaCost:
                  type: string
                type:
                  type: string
                rulesText:
                  type: string
                expansion:
                  type: string
                artist:
                  type: string
                image:
                  type: string
      responses:
        '200':
          description: Card updated successfully
        '400':
          description: Bad request

    delete:
      summary: Delete a card by ID
      parameters:
        - name: card_id
          in: path
          description: ID of the card to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Card deleted successfully
        '404':
          description: Card not found